use voyage_vista;
select * from uber;
alter table uber rename column `START_DATE*` to START_DATE;
alter table uber rename column `END_DATE*` to END_DATE;
alter table uber rename column `CATEGORY*` to CATEGORY;
alter table uber rename column `START*` to PICKUP_LOCATION;
alter table uber rename column `DESTINATION` to `DROP-OFF_LOCATION`;
alter table uber rename column `MILES*` to MILES;
alter table uber rename column `PURPOSE*` to PURPOSE;
delete from uber where START_DATE='Totals';
alter table uber add column START_DAY_DATE date, add column START_DAY_TIME time;
update uber set START_DAY_DATE= str_to_date(substring_index(START_DATE,' ',1), '%m/%d/%Y'),START_DAY_TIME=str_to_date(substring_index(START_DATE,' ',-1), '%H:%i');
alter table uber add column END_DAY_DATE date, add column END_DAY_TIME time;
update uber set END_DAY_DATE= str_to_date(substring_index(END_DATE,' ',1), '%m/%d/%Y'),END_DAY_TIME=str_to_date(substring_index(END_DATE,' ',-1), '%H:%i');
alter table uber drop column START_DATE;
alter table uber drop column END_DATE;
ALTER TABLE uber ADD START_DATE VARCHAR(25);
UPDATE uber SET START_DATE = CONCAT(START_DAY_DATE,' ', START_DAY_TIME);
ALTER TABLE uber ADD END_DATE VARCHAR(25);
UPDATE uber SET END_DATE = CONCAT(END_DAY_DATE,' ', END_DAY_TIME);